Adding error handling detection, fixing strict::run
strict::run used a conditional, forcing everything to be run in a weird
context where strict mode would ignore errors. This is bad for unit
testing, especially when you expect strict mode and this error context
to be each tested separately.

Also alphabetized functions.

diff --git a/libstrict b/libstrict
--- a/libstrict
+++ b/libstrict
@@ -3,35 +3,52 @@
 . bpm
 bpm::include assign
 
-# Enables "strict mode" for Bash, based off [unofficial bash strict mode].
-# Errors will kill the program.  Accessing undefined variables will cause
-# errors (and exit the program).  Commands in pipelines that return a non-zero
-# status code will also cause errors and kill the program.  An ERR trap is also
-# enabled that will produce a stack trace when errors happen.
+# Check if errors are ignored. Be careful, calling this function inside of
+# a conditional will completely change the answer.
 #
-# Not all errors are caught. There's an error context in Bash that ignores
-# errors, so be careful when you intend to rely on this behavior. It is only
-# here as a safety net to catch you in case of problems, not a babysitter
-# to prevent you from starting the house on fire.
+# $1 - Result should be placed in this variable.
 #
-# This is intended to be used at the beginning of your shell scripts in order
-# to ensure correctness in your programming.
+# The value that's stored in the variable named by `$1` will be one of these
+# values:
+#
+# * `true` - Errors are honored.
+# * `false` - Errors are not honored.
+#
+# By "honored", it means that the program should terminate when `set -eE` is
+# enabled.
 #
 # Examples
 #
-#   #!/usr/bin/env bash
-#   . bpm
-#   bpm::include strict
-#   strict::mode
-#
-# [unofficial bash strict mode]: http://redsymbol.net/articles/unofficial-bash-strict-mode/
+#   # Using ||, &&, or any other conditional changes the context.
+#   strict::checkErrors || echo "Errors in conditionals are not honored."
 #
 # Returns nothing.
-strict::mode() {
-    set -eEu -o pipefail
-    shopt -s extdebug
-    IFS=$'\t\n'
-    trap 'strict::failure $?' ERR
+strict::checkErrorsHonored() {
+    local result
+
+    result="$(
+        # Subshells are used to help avoid cleanup.
+        set +eE
+        trap - ERR
+
+        checkIfIgnored() {
+            (
+                set -eE
+                false
+                true
+            )
+        }
+
+        checkIfIgnored
+
+        if [[ $? -eq 0 ]]; then
+            echo false
+        else
+            echo true
+        fi
+    )"
+
+    local "$1" && assign::value "$1" "$result"
 }
 
 
@@ -121,6 +138,38 @@ strict::failure() (
 )
 
 
+# Enables "strict mode" for Bash, based off [unofficial bash strict mode].
+# Errors will kill the program.  Accessing undefined variables will cause
+# errors (and exit the program).  Commands in pipelines that return a non-zero
+# status code will also cause errors and kill the program.  An ERR trap is also
+# enabled that will produce a stack trace when errors happen.
+#
+# Not all errors are caught. There's an error context in Bash that ignores
+# errors, so be careful when you intend to rely on this behavior. It is only
+# here as a safety net to catch you in case of problems, not a babysitter
+# to prevent you from starting the house on fire.
+#
+# This is intended to be used at the beginning of your shell scripts in order
+# to ensure correctness in your programming.
+#
+# Examples
+#
+#   #!/usr/bin/env bash
+#   . bpm
+#   bpm::include strict
+#   strict::mode
+#
+# [unofficial bash strict mode]: http://redsymbol.net/articles/unofficial-bash-strict-mode/
+#
+# Returns nothing.
+strict::mode() {
+    set -eEu -o pipefail
+    shopt -s extdebug
+    IFS=$'\t\n'
+    trap 'strict::failure $?' ERR
+}
+
+
 # Runs a command and captures its return code, even when strict mode is
 # enabled.  The variable name you specify is set to the return code of the
 # command.
@@ -168,10 +217,10 @@ strict::run() {
     # however, want strict mode enabled inside the subshell.
     set +eE
     trap - ERR
-
     (
         eval "$restoreErrors"
-        "$@" || exit $?
+        "$@"
+        exit "$?"
     )
 
     result=$?
